version: 1.2
notebooks:
  - name: Intro
    path: /notebooks/0_Intro_to_Jupyter_Notebooks_OPTIONAL.ipynb 
    publish: true
  - name: VariantDiscoveryTutorial
    path: /notebooks/1-gatk-germline-variant-discovery-tutorial.ipynb
    publish: true
  - name: GatkHardFilteringTutorial
    path: /notebooks/2-gatk-hard-filtering-tutorial.ipynb
    publish: true
  - name: BigQueryCohortAnalysis
    path: /notebooks/2_BigQuery_cohort_analysis.ipynb
    publish: true
  - name: AccessPlotPublicBigQueryData
    path: /notebooks/3_Access_and_plot_public_BigQuery_data.ipynb
    publish: true
  - name: ClusterAnalysis
    path: /notebooks/Cluster_Analysis_Tetralogy_of_Fallot.ipynb
    publish: true
  - name: GWASInitialAnalysisBlank
    path: /notebooks/GWAS_initial_analysis_blank.ipynb
    publish: true
  - name: GWASInitialAnalysisCompleted
    path: /notebooks/GWAS_initial_analysis_completed.ipynb
    publish: true
  - name: SomaticCNATutorial
    path: /notebooks/Somatic-CNA-Tutorial.ipynb
    publish: true
  - name: SomaticMutect2Tutorial
    path: /notebooks/Somatic-Mutect2-Tutorial.ipynb
    publish: true
  - name: WorkflowCostEstimator
    path: /notebooks/Workflow-Cost-Estimator.ipynb
    publish: true
  - name: GatkCnnTutorial
    path: /notebooks/gatk-cnn-tutorial.ipynb
    publish: true
  - name: GnomADWithBigQuery
    path: /notebooks/gnomAD-with-BigQuery.ipynb
    publish: true
  - name: GnomADWithHail
    path: /notebooks/gnomAD-with-Hail.ipynb
    publish: true
